### ISSUE TITLE
Option --no-badge does not work

### ISSUE THREAD

**Issue by bradyt** [pulyaevskiy/test-coverage#15]
If I try the following,

```
git clone https://github.com/pulyaevskiy/test-coverage.git
cd test-coverage/test/stub-package
rm coverage_badge.svg
pub get
pub run test_coverage --no-badge
```
Then the `coverage_badge.svg` file is back.

```
$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
```

**Comment by pulyaevskiy** [comment]
Fix released as 0.4.3. See #21 for details.

**Comment by bradyt** [comment]
I'm confused. I still see the badge file made with the recipe I gave above. I'm using the dart executable that comes with current flutter stable, 2.8.4.

**Comment by bradyt** [comment]
@matanlurey, any ideas?

**Comment by jagandeepbrar** [comment]
I'm also experiencing the same thing, latest version of `test_coverage` and running `test_coverage --no-badge` is still producing the badge SVG at the root of the project.

**Comment by dellgreen** [comment]
Even with 0.4.3, the badge file is still produced
